default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: tricks
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: tricks_dev

test:
  <<: *default
  database: tricks_test