development:
  adapter: postgresql
  encoding: unicode
  database: tricks_development
  pool: 5
  username: jtaylor
  password: tricks24

test:
  adapter: postgresql
  encoding: unicode
  database: tricks_test
  pool: 5
  username: jtaylor
  password: 